language: node_js
node_js:
  - "0.10"

branches:
  only:
  - master
  - develop

before_script:
  - sudo npm install gulp -g

script:
  - npm run test:coverage
  - npm run build

after_success:
  - npm run coveralls

